
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STECH
 */
public class Search_form extends javax.swing.JFrame {

    /**
     * Creates new form Search_form
     */
    public Search_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        car_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_by_name = new javax.swing.JButton();
        search_by_model = new javax.swing.JButton();
        search_by_manufacturer = new javax.swing.JButton();
        Search_by_price = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        search_by_no = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Cars");

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");

        car_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_searchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Number", "Name", "Manufacturer", "Model", "Price", "Extra"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        search_by_name.setBackground(new java.awt.Color(255, 255, 102));
        search_by_name.setText("Search By Name ");
        search_by_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_nameActionPerformed(evt);
            }
        });

        search_by_model.setBackground(new java.awt.Color(255, 204, 204));
        search_by_model.setText("Search By Model");
        search_by_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_modelActionPerformed(evt);
            }
        });

        search_by_manufacturer.setBackground(new java.awt.Color(51, 255, 0));
        search_by_manufacturer.setText("Search By Manufacturer");
        search_by_manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_manufacturerActionPerformed(evt);
            }
        });

        Search_by_price.setBackground(new java.awt.Color(255, 255, 255));
        Search_by_price.setText("Search By Price Range");
        Search_by_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_by_priceActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(255, 0, 0));
        clear_btn.setText("Clear");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Enter Car No, Name , Manufacturer, Model or Max Price Range");

        search_by_no.setBackground(new java.awt.Color(102, 153, 255));
        search_by_no.setText("Search By Car No");
        search_by_no.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        search_by_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_by_noActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setText("Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 3, 20)); // NOI18N
        jLabel2.setText("Search Cars");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Search_by_price, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search_by_no, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search_by_name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(search_by_manufacturer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_by_model)
                    .addComponent(car_search, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_by_model, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(search_by_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(search_by_manufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Search_by_price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(search_by_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(756, 412));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void car_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_car_searchActionPerformed

    private void search_by_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_modelActionPerformed
        clear_table();
        
        String search_model = car_search.getText();
         
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` WHERE `model` = ?";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, search_model);
                     rs = ps.executeQuery();
                     
         
                     while(rs.next()){    
                     
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,model,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Search_form.class.getName()).log(Level.SEVERE, null, ex);
                 }  // TODO add your handling code here:
    }//GEN-LAST:event_search_by_modelActionPerformed
      
    
    private void search_by_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_nameActionPerformed
         clear_table();
           String search_name = car_search.getText();
         
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` WHERE `car_name` = ?";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, search_name);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Search_form.class.getName()).log(Level.SEVERE, null, ex);
                 }  
         
        // TODO add your handling code here:
    }//GEN-LAST:event_search_by_nameActionPerformed

 void clear_table(){
     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                      
                       int i = tblModel.getRowCount()-1;
                    if(i>=0){
                      while(tblModel.getRowCount()>=0) {
                          
                          tblModel.removeRow(i);
                          i--;
                      
                      }
                    }                  
 
 }   
    
    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
               clear_table();             
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void search_by_manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_manufacturerActionPerformed
                 clear_table();
           String search_manufacturer = car_search.getText();
         
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` WHERE `manufacturer` = ?";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, search_manufacturer);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Search_form.class.getName()).log(Level.SEVERE, null, ex);
                 }  
                 

// TODO add your handling code here:
    }//GEN-LAST:event_search_by_manufacturerActionPerformed

    private void search_by_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_by_noActionPerformed
                        clear_table();
           String search_car_no = car_search.getText();
         
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` WHERE `car_no` = ?";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, search_car_no);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Search_form.class.getName()).log(Level.SEVERE, null, ex);
                 }          



// TODO add your handling code here:
    }//GEN-LAST:event_search_by_noActionPerformed

    private void Search_by_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_by_priceActionPerformed
                                     clear_table();
           String search_by_price = car_search.getText();
         
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` WHERE `price` <= ?";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     ps.setString(1, search_by_price);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Search_form.class.getName()).log(Level.SEVERE, null, ex);
                 }          

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_by_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.dispose();
                java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cars_sales().setVisible(true);
            }
        });

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search_by_price;
    private javax.swing.JTextField car_search;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search_by_manufacturer;
    private javax.swing.JButton search_by_model;
    private javax.swing.JButton search_by_name;
    private javax.swing.JButton search_by_no;
    // End of variables declaration//GEN-END:variables
}
