
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STECH
 */
public class Show_cars_form extends javax.swing.JFrame {

    /**
     * Creates new form Show_cars_form
     */
    public Show_cars_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        view_all_cars = new javax.swing.JButton();
        sort_no = new javax.swing.JButton();
        sort_name = new javax.swing.JButton();
        sort_model = new javax.swing.JButton();
        sort_price = new javax.swing.JButton();
        main_menu_btn = new javax.swing.JButton();
        sort_manufacturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Details");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Number", "Car Name", "Manufacturer", "Model", "Price", "Extra Details"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        view_all_cars.setText("View All Cars");
        view_all_cars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_all_carsActionPerformed(evt);
            }
        });

        sort_no.setText("Sort By Car Number");
        sort_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_noActionPerformed(evt);
            }
        });

        sort_name.setText("Sort By Car Name");
        sort_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_nameActionPerformed(evt);
            }
        });

        sort_model.setText("Sort By Model");
        sort_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_modelActionPerformed(evt);
            }
        });

        sort_price.setText("Sort By Price");
        sort_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_priceActionPerformed(evt);
            }
        });

        main_menu_btn.setText("Main Menu");
        main_menu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_menu_btnActionPerformed(evt);
            }
        });

        sort_manufacturer.setText("Sort By Manufacturer");
        sort_manufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort_manufacturerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Car Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sort_no)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sort_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sort_manufacturer)
                        .addGap(18, 18, 18)
                        .addComponent(sort_model)
                        .addGap(18, 18, 18)
                        .addComponent(sort_price)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(main_menu_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(view_all_cars)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_all_cars)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort_no)
                    .addComponent(sort_name)
                    .addComponent(sort_model)
                    .addComponent(sort_price)
                    .addComponent(main_menu_btn)
                    .addComponent(sort_manufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(772, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void view_all_carsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_all_carsActionPerformed
               clear_table();
         PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }          
                      
// TODO add your handling code here:
    }//GEN-LAST:event_view_all_carsActionPerformed

    private void sort_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_noActionPerformed
                 clear_table();
                 PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` ORDER BY `car_no`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }                           

        // TODO add your handling code here:
    }//GEN-LAST:event_sort_noActionPerformed

    private void sort_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_nameActionPerformed
                 clear_table();
                 PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` ORDER BY `car_name`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }                           

        // TODO add your handling code here:
    }//GEN-LAST:event_sort_nameActionPerformed

    private void sort_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_modelActionPerformed
                 clear_table();
                 PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` ORDER BY `model`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }                           


        // TODO add your handling code here:
    }//GEN-LAST:event_sort_modelActionPerformed

    private void sort_manufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_manufacturerActionPerformed
                 clear_table();
                 PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` ORDER BY `manufacturer`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }                           


        // TODO add your handling code here:
    }//GEN-LAST:event_sort_manufacturerActionPerformed

    private void sort_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort_priceActionPerformed
                 clear_table();
                 PreparedStatement ps;
                 String registerUserQuery = "SELECT * FROM `cars` ORDER BY `price`";
                  ResultSet rs;
                 
                 try {
                     ps = My_CONX.getConnection().prepareStatement(registerUserQuery);
                     rs = ps.executeQuery();
                     
                     while(rs.next()){    
                     
                  
                     String carno = rs.getString("car_no");
                     String carname = rs.getString("car_name");
                     String carmanufacturer = rs.getString("manufacturer");
                     String model = rs.getString("model");
                     String carprice = rs.getString("price");
                     String extra = rs.getString("extra");
                     
                     String tbData[] = {carno,carname,carmanufacturer,model,carprice,extra};
                     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                     
                     tblModel.addRow(tbData);
                     tblModel.getRowCount();
                     }
                     
                 } catch (SQLException ex) {
                     Logger.getLogger(Show_cars_form.class.getName()).log(Level.SEVERE, null, ex);
                 }                           


        // TODO add your handling code here:
    }//GEN-LAST:event_sort_priceActionPerformed

    private void main_menu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_menu_btnActionPerformed
                 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cars_sales().setVisible(true);
            }
        });
        this.dispose();
                

        // TODO add your handling code here:
    }//GEN-LAST:event_main_menu_btnActionPerformed

    void clear_table(){
     DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                      
                       int i = tblModel.getRowCount()-1;
                    if(i>=0){
                      while(tblModel.getRowCount()>=0) {
                          
                          tblModel.removeRow(i);
                          i--;
                      
                      }
                    }                  
 
 }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_cars_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_cars_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_cars_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_cars_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_cars_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton main_menu_btn;
    private javax.swing.JButton sort_manufacturer;
    private javax.swing.JButton sort_model;
    private javax.swing.JButton sort_name;
    private javax.swing.JButton sort_no;
    private javax.swing.JButton sort_price;
    private javax.swing.JButton view_all_cars;
    // End of variables declaration//GEN-END:variables
}
